### ISSUE TITLE
Fix URLs referencing the packaged library

### ISSUE THREAD

**Issue by gmcabiato** [portittech/pay-with-toonie-doc#6]
Update URLs with:

- Pay With Toonie JS SDK [npm package url](https://www.npmjs.com/package/@portittech/pay-with-toonie)
- Pay With Toonie JS SDK [javascript component](https://unpkg.com/@portittech/pay-with-toonie/dist/pay-with-toonie.dist.js)
- Pay With Toonie JS SDK [css styles](https://unpkg.com/@portittech/pay-with-toonie/dist/pay-with-toonie.dist.css)

**Comment by marco-kuama** [comment]
Checked on the README and the urls are correct
